export const SET_TITLE = "SET_TITLE";
export const SET_PREPARATION = "SET_PREPARATION";
export const SET_PREPARATION_TIME = "SET_PREPARATION_TIME";
export const SET_INGREDIENTS = "SET_INGREDIENTS";

export const POST_RECIPE_REQUESTED = "POST_RECIPE_REQUESTED";
export const POST_RECIPE_DONE = "POST_RECIPE_DONE";
export const POST_RECIPE_FAILED = "POST_RECIPE_FAILED";